# coding: utf-8

"""
    Verbatim AI — GenAI Backend API

      ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 4 domains: - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (document chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 

    The version of the OpenAPI document: v1
    Contact: contact@verbatim-ai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from verbatim_client.api.document_api import DocumentApi


class TestDocumentApi(unittest.TestCase):
    """DocumentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DocumentApi()

    def tearDown(self) -> None:
        pass

    def test_commit_upload(self) -> None:
        """Test case for commit_upload

        Commit a previously initialized upload
        """
        pass

    def test_delete3(self) -> None:
        """Test case for delete3

        Delete a document
        """
        pass

    def test_download_url1(self) -> None:
        """Test case for download_url1

        Get a presigned download URL
        """
        pass

    def test_get3(self) -> None:
        """Test case for get3

        Get a document
        """
        pass

    def test_init_upload(self) -> None:
        """Test case for init_upload

        Initialize a direct-to-storage upload
        """
        pass

    def test_list5(self) -> None:
        """Test case for list5

        List documents
        """
        pass

    def test_list_supported_documents(self) -> None:
        """Test case for list_supported_documents

        List accepted content types
        """
        pass

    def test_preview_urls1(self) -> None:
        """Test case for preview_urls1

        Get presigned preview URLs
        """
        pass

    def test_reinit_upload(self) -> None:
        """Test case for reinit_upload

        Re-initialize a document for a new upload
        """
        pass

    def test_search(self) -> None:
        """Test case for search

        Search documents
        """
        pass

    def test_status(self) -> None:
        """Test case for status

        Get a document's status
        """
        pass

    def test_summary(self) -> None:
        """Test case for summary

        Get a document summary
        """
        pass

    def test_update3(self) -> None:
        """Test case for update3

        Update a document
        """
        pass


if __name__ == '__main__':
    unittest.main()
