# coding: utf-8

"""
    Verbatim AI — GenAI Backend API

      ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 5 domains: - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Chunk** — one embeddable piece of a document, produced by ingestion. The unit retrieval actually returns. - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (the chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 

    The version of the OpenAPI document: v1
    Contact: contact@verbatim-ai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from verbatim_client.models.agent import Agent

class TestAgent(unittest.TestCase):
    """Agent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Agent:
        """Test Agent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Agent`
        """
        model = Agent()
        if include_optional:
            return Agent(
                id = '550e8400-e29b-41d4-a716-446655440000',
                name = 'Support assistant',
                description = 'Answers customer questions from the support knowledge base, in the customer's language.',
                lock = False,
                top_k = 10,
                rerank = True,
                rerank_top_k = 3,
                context = 'Use the following document excerpts to answer the user:',
                behaviour = 'Answer only from the excerpts provided. When they do not contain the answer, say so plainly.',
                spirit = 'Be precise, concise and factual.',
                use_history = True,
                history_size = 10,
                thinking_mode = 'HIGH',
                temperature = 0.2,
                rerank_model = 'gemma4',
                base_model = 'mistral',
                created_at = '2026-04-23T04:06:51Z',
                updated_at = '2026-04-23T04:06:51Z',
                default = False
            )
        else:
            return Agent(
                id = '550e8400-e29b-41d4-a716-446655440000',
                name = 'Support assistant',
                lock = False,
                top_k = 10,
                rerank = True,
                use_history = True,
                thinking_mode = 'HIGH',
                created_at = '2026-04-23T04:06:51Z',
                updated_at = '2026-04-23T04:06:51Z',
                default = False,
        )
        """

    def testAgent(self):
        """Test Agent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
