# coding: utf-8

"""
    Verbatim AI — GenAI Backend API

    Backend API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform.  ## Concepts  - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (document chunks used as context).  ## Authentication  Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## Conventions  - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. 

    The version of the OpenAPI document: v1
    Contact: contact@verbatim-ai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from verbatim_client.api.post_api import PostApi


class TestPostApi(unittest.TestCase):
    """PostApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PostApi()

    def tearDown(self) -> None:
        pass

    def test_attachment(self) -> None:
        """Test case for attachment

        Attachments from a post
        """
        pass

    def test_delete3(self) -> None:
        """Test case for delete3

        Delete a post
        """
        pass

    def test_download_url(self) -> None:
        """Test case for download_url

        Get a presigned download URL
        """
        pass

    def test_get3(self) -> None:
        """Test case for get3

        Get a post
        """
        pass

    def test_list2(self) -> None:
        """Test case for list2

        List posts
        """
        pass

    def test_preview_urls(self) -> None:
        """Test case for preview_urls

        Get presigned preview URLs
        """
        pass

    def test_query(self) -> None:
        """Test case for query

        Send a query
        """
        pass


if __name__ == '__main__':
    unittest.main()
