# coding: utf-8

"""
    Verbatim AI — GenAI Backend API

      ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 5 domains: - **Corpus** — a knowledge base. Holds documents, threads, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Chunk** — one embeddable piece of a document, produced by ingestion. The unit retrieval actually returns. - **Thread** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a thread. Answers reference attachments (the chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 

    The version of the OpenAPI document: v1
    Contact: contact@verbatim-ai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from verbatim_client.api.thread_api import ThreadApi


class TestThreadApi(unittest.TestCase):
    """ThreadApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ThreadApi()

    def tearDown(self) -> None:
        pass

    def test_create(self) -> None:
        """Test case for create

        Create a thread
        """
        pass

    def test_create1(self) -> None:
        """Test case for create1

        Create a thread
        """
        pass

    def test_delete(self) -> None:
        """Test case for delete

        Delete a thread
        """
        pass

    def test_delete1(self) -> None:
        """Test case for delete1

        Delete a thread
        """
        pass

    def test_get(self) -> None:
        """Test case for get

        Get a thread
        """
        pass

    def test_get1(self) -> None:
        """Test case for get1

        Get a thread
        """
        pass

    def test_list(self) -> None:
        """Test case for list

        List threads
        """
        pass

    def test_list1(self) -> None:
        """Test case for list1

        List threads
        """
        pass

    def test_search(self) -> None:
        """Test case for search

        Search threads
        """
        pass

    def test_search1(self) -> None:
        """Test case for search1

        Search threads
        """
        pass

    def test_update(self) -> None:
        """Test case for update

        Update a thread
        """
        pass

    def test_update1(self) -> None:
        """Test case for update1

        Update a thread
        """
        pass


if __name__ == '__main__':
    unittest.main()
