# coding: utf-8

"""
    Verbatim AI — GenAI Backend API

    Backend API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform.  ## Concepts  - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (document chunks used as context).  ## Authentication  Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## Conventions  - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. 

    The version of the OpenAPI document: v1
    Contact: contact@verbatim-ai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from verbatim_client.models.key_item_response import KeyItemResponse

class TestKeyItemResponse(unittest.TestCase):
    """KeyItemResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KeyItemResponse:
        """Test KeyItemResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KeyItemResponse`
        """
        model = KeyItemResponse()
        if include_optional:
            return KeyItemResponse(
                org_id = '550e8400-e29b-41d4-a716-446655440000',
                item = verbatim_client.models.key.Key(
                    id = '550e8400-e29b-41d4-a716-446655440000', 
                    org_id = '550e8400-e29b-41d4-a716-446655440000', 
                    name = 'support-backend-prod', 
                    description = 'Production signing key for the support backend.', 
                    format = 'PEM', 
                    preview = '-----BEGIN PUBLIC KEY----- MIICIjANBgkqhkiG9w0BAQEFAAOCAg8...', 
                    state = 'INACTIVE', 
                    created_at = '2026-04-23T04:06:51Z', 
                    updated_at = '2026-04-23T04:06:51Z', )
            )
        else:
            return KeyItemResponse(
                org_id = '550e8400-e29b-41d4-a716-446655440000',
        )
        """

    def testKeyItemResponse(self):
        """Test KeyItemResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
