# coding: utf-8

"""
    Verbatim AI — GenAI Backend API

      ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 5 domains: - **Corpus** — a knowledge base. Holds documents, threads, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Chunk** — one embeddable piece of a document, produced by ingestion. The unit retrieval actually returns. - **Thread** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a thread. Answers reference attachments (the chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 

    The version of the OpenAPI document: v1
    Contact: contact@verbatim-ai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Chunk(BaseModel):
    """
    One embeddable piece of a document: the text that was vectorised, where it came from, and the metadata the ingestion pipeline attached to it.
    """ # noqa: E501
    id: UUID = Field(description="Unique identifier of the chunk (UUIDv4). Same id the `attachment` records of a post point at.", json_schema_extra={"examples": ["550e8400-e29b-41d4-a716-446655440000"]})
    document_id: UUID = Field(description="Document the chunk was cut from.", alias="documentId", json_schema_extra={"examples": ["550e8400-e29b-41d4-a716-446655440001"]})
    corpus_id: UUID = Field(description="Corpus owning the document. Not stored on the chunk — resolved through the document — and reported here because it is half of the storage key of `body`.", alias="corpusId", json_schema_extra={"examples": ["550e8400-e29b-41d4-a716-446655440002"]})
    pages: Optional[List[StrictInt]] = Field(default=None, description="1-based page numbers the chunk spans, ascending. A chunk is built from consecutive elements and may cross page boundaries, so this is a span rather than a single page. **Empty** for a chunk that belongs to no page in particular — the document summary is the usual case.", json_schema_extra={"examples": [[2, 3, 4]]})
    hash: Optional[StrictStr] = Field(default=None, description="MD5 of the chunk body as it was pushed to storage. Equal hashes mean equal text, which is how duplicated content is found across documents. Read-only — it is computed by the ingestion pipeline.", json_schema_extra={"examples": ["9e107d9d372bb6826bd81d3542a419d6"]})
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Arbitrary JSON metadata attached by the ingestion pipeline. `kind` is the key the platform itself sets — `chunk` for a piece of the document, `summary` for the generated summary.", json_schema_extra={"examples": [{"kind": "chunk", "section": "Article 4"}]})
    body: Optional[StrictStr] = Field(default=None, description="The chunk text, read from object storage. Present on `GET /v1/chunk/{chunkId}`, and on the listings only when `body=true` was passed. An empty string means the row exists but its stored body does not — a broken chunk, which is one of the things this API exists to surface.", json_schema_extra={"examples": ["Article 4 — The supplier shall deliver within thirty (30) days…"]})
    __properties: ClassVar[List[str]] = ["id", "documentId", "corpusId", "pages", "hash", "metadata", "body"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Chunk from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Chunk from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "documentId": obj.get("documentId"),
            "corpusId": obj.get("corpusId"),
            "pages": obj.get("pages"),
            "hash": obj.get("hash"),
            "metadata": obj.get("metadata"),
            "body": obj.get("body")
        })
        return _obj


