# coding: utf-8

"""
    Verbatim AI — GenAI Backend API

      ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 5 domains: - **Corpus** — a knowledge base. Holds documents, threads, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Chunk** — one embeddable piece of a document, produced by ingestion. The unit retrieval actually returns. - **Thread** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a thread. Answers reference attachments (the chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 

    The version of the OpenAPI document: v1
    Contact: contact@verbatim-ai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Document(BaseModel):
    """
    A file ingested into a corpus. Holds metadata; the binary content is streamed via the download endpoint.
    """ # noqa: E501
    id: UUID = Field(description="Unique identifier of the document (UUIDv4).", json_schema_extra={"examples": ["550e8400-e29b-41d4-a716-446655440000"]})
    corpus_id: UUID = Field(description="ID of the corpus this document belongs to.", alias="corpusId", json_schema_extra={"examples": ["550e8400-e29b-41d4-a716-446655440000"]})
    user_id: Optional[StrictStr] = Field(default=None, description="Identifier of the user who uploaded the document. May be null when no user identity was provided at upload time.", alias="userId", json_schema_extra={"examples": ["550e8400-e29b-41d4-a716-446655440099"]})
    filename: StrictStr = Field(description="Original filename, as provided at upload time.", json_schema_extra={"examples": ["annual-report-2025.pdf"]})
    content_type: StrictStr = Field(description="MIME content type of the file.", alias="contentType", json_schema_extra={"examples": ["application/pdf"]})
    status: StrictStr = Field(description="Lifecycle status of the document. AWAITING_UPLOAD: created via init, file not yet uploaded. READY: ingestion completed.", json_schema_extra={"examples": ["READY"]})
    path: Optional[StrictStr] = Field(default=None, description="Internal storage path of the file. Opaque — use the download endpoint instead.")
    provider: Optional[StrictStr] = Field(default=None, description="Free-form label identifying the source of the document.", json_schema_extra={"examples": ["user"]})
    lang: Optional[StrictStr] = Field(default=None, description="ISO-639 language code used during ingestion.", json_schema_extra={"examples": ["fr"]})
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Arbitrary JSON metadata attached to the document. Stored as JSONB.", json_schema_extra={"examples": [{"source": "user", "team": "legal"}]})
    tags: Optional[List[StrictStr]] = Field(default=None, description="Free-form labels used to classify the document. Filter on them with `GET /v1/doc/?tags=…`. Null when the document carries no tag.", json_schema_extra={"examples": [["legal", "2026"]]})
    chunk: Optional[Dict[str, Any]] = Field(default=None, description="Chunking configuration used when ingesting this document — an Unstructured chunking option set (`strategy`, `max_characters`, `overlap`, …). Null means the platform default was used (`by_title`, `max_characters: 10000`, `combine_text_under_n_chars: 1000`). See `DocumentInitRequest.chunk` for the full key reference.", json_schema_extra={"examples": [{"strategy": "by_title", "max_characters": 10000, "combine_text_under_n_chars": 1000}]})
    doc_create: datetime = Field(description="Creation date of the **source** document — the file — as opposed to `createdAt`, which is when the platform first saw it (ISO-8601, UTC). Always present: when the upload declared no date, this is the upload instant.", alias="docCreate", json_schema_extra={"examples": ["2026-01-15T10:30:00Z"]})
    doc_update: datetime = Field(description="Last-modified date of the **source** document (ISO-8601, UTC), on the same terms as `docCreate`. Always present, and the one of the two that moves: replacing the content with `PUT /v1/doc/{id}/init` re-stamps it with the moment of that call. Correct it with `PATCH /v1/doc/{id}` when the new file's real modification date is known.", alias="docUpdate", json_schema_extra={"examples": ["2026-04-01T08:00:00Z"]})
    created_at: datetime = Field(description="Date the document was uploaded to the platform (ISO-8601, UTC).", alias="createdAt", json_schema_extra={"examples": ["2026-04-23T04:06:51Z"]})
    updated_at: datetime = Field(description="Last update timestamp of the document row (ISO-8601, UTC).", alias="updatedAt", json_schema_extra={"examples": ["2026-04-23T04:06:51Z"]})
    size: Optional[StrictInt] = Field(default=None, description="Size of the source file in bytes. Set after ingestion.", json_schema_extra={"examples": [204800]})
    storage: Optional[StrictInt] = Field(default=None, description="Bytes this document occupies on the platform — the source file **plus** everything derived from it: rendered page previews, the markdown conversion, the summary and the embedding payloads. Always larger than `size` once ingested, often by several times for a document that renders and chunks. This is the figure the storage totals of `GET /v1/usage/*` are built from. `0` means *not computed yet* — the processing pipeline reports it during ingestion, so it stays `0` until then.", json_schema_extra={"examples": [1048576]})
    nb_chunks: Optional[StrictInt] = Field(default=None, description="Number of chunks this document was split into — the passages `GET /v1/chunk/q?documentId=…` returns for it. `0` means *not computed yet* — the processing pipeline reports it during ingestion, so it stays `0` until then.", alias="nbChunks", json_schema_extra={"examples": [312]})
    tokens: Optional[StrictInt] = Field(default=None, description="Number of LLM tokens consumed to produce the summary. Set after ingestion.", json_schema_extra={"examples": [150]})
    nb_words: Optional[StrictInt] = Field(default=None, description="Number of words in the source document. Set after ingestion.", alias="nbWords", json_schema_extra={"examples": [1200]})
    nb_pages: Optional[StrictInt] = Field(default=None, description="Number of pages of the source document. `0` means *not counted yet* — the rendering pipeline reports it during ingestion, so it stays `0` until then (and for formats that have no pages). Use it to bound the `pages` indices of `GET /v1/doc/{id}/preview-urls`, whose valid range is `0..nbPages-1`.", alias="nbPages", json_schema_extra={"examples": [24]})
    __properties: ClassVar[List[str]] = ["id", "corpusId", "userId", "filename", "contentType", "status", "path", "provider", "lang", "metadata", "tags", "chunk", "docCreate", "docUpdate", "createdAt", "updatedAt", "size", "storage", "nbChunks", "tokens", "nbWords", "nbPages"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['AWAITING_UPLOAD', 'PENDING', 'PROCESSING', 'READY', 'FAILED']):
            raise ValueError("must be one of enum values ('AWAITING_UPLOAD', 'PENDING', 'PROCESSING', 'READY', 'FAILED')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Document from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Document from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "corpusId": obj.get("corpusId"),
            "userId": obj.get("userId"),
            "filename": obj.get("filename"),
            "contentType": obj.get("contentType"),
            "status": obj.get("status"),
            "path": obj.get("path"),
            "provider": obj.get("provider"),
            "lang": obj.get("lang"),
            "metadata": obj.get("metadata"),
            "tags": obj.get("tags"),
            "chunk": obj.get("chunk"),
            "docCreate": obj.get("docCreate"),
            "docUpdate": obj.get("docUpdate"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "size": obj.get("size"),
            "storage": obj.get("storage"),
            "nbChunks": obj.get("nbChunks"),
            "tokens": obj.get("tokens"),
            "nbWords": obj.get("nbWords"),
            "nbPages": obj.get("nbPages")
        })
        return _obj


