# coding: utf-8

"""
    Verbatim AI — GenAI Backend API

      ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 4 domains: - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (document chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 

    The version of the OpenAPI document: v1
    Contact: contact@verbatim-ai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from verbatim_client.models.session import Session
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SessionListResponse(BaseModel):
    """
    Paginated list of sessions. Echoes the filter that produced it.
    """ # noqa: E501
    corpus_id: Optional[UUID] = Field(default=None, description="Echo of the corpus filter, when the listing was filtered by corpus.", alias="corpusId", json_schema_extra={"examples": ["550e8400-e29b-41d4-a716-446655440000"]})
    user_id: Optional[StrictStr] = Field(default=None, description="Echo of the user filter, when the listing was filtered by user.", alias="userId", json_schema_extra={"examples": ["user_42"]})
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Echo of the metadata fragment used to filter the listing, when applicable.", json_schema_extra={"examples": [{"customer_id": "42"}]})
    page_index: StrictInt = Field(description="Zero-based index of the returned page.", alias="pageIndex", json_schema_extra={"examples": [0]})
    page_size: StrictInt = Field(description="Number of items requested per page.", alias="pageSize", json_schema_extra={"examples": [25]})
    total: StrictInt = Field(description="Total number of sessions matching the filter across every page.", json_schema_extra={"examples": [42]})
    items: Optional[List[Session]] = Field(default=None, description="Sessions contained in this page, newest first.")
    __properties: ClassVar[List[str]] = ["corpusId", "userId", "metadata", "pageIndex", "pageSize", "total", "items"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SessionListResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item_items in self.items:
                _items.append(_item_items.to_dict() if _item_items is not None else None)
            _dict['items'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SessionListResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "corpusId": obj.get("corpusId"),
            "userId": obj.get("userId"),
            "metadata": obj.get("metadata"),
            "pageIndex": obj.get("pageIndex"),
            "pageSize": obj.get("pageSize"),
            "total": obj.get("total"),
            "items": [Session.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None
        })
        return _obj


